// This file is automatically generated.
// Please do not change this file!

// Use type safe message keys with `next-intl`
type Messages = typeof import('./messages/en.json');

type NestedMessages = {
  [key: string]: string | NestedMessages;
};

type IntlMessages = Messages;

export type { Messages, NestedMessages, IntlMessages };
